branches:
  only:
    - master
matrix:
  include:
    - language: cpp
      os: linux
      before_install:
        - pip install --user cpplint
      script:
        - make lint
        - make test
notifications:
  email: false
