branches:
  only:
    - master
matrix:
  include:
    - language: cpp
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      before_install:
        - eval "CC=gcc-8 && CXX=g++-8"
        - pip install --user cpplint
      script:
        - make lint
        - make test
notifications:
  email: false
